#This is the first line in lore for both types of boots.
firstline: "Allows you to fly like you always wanted"

#This is item Material used to charge premiumboots
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
chargeitem: "WIND_CHARGE"

#This indicates how many seconds of flying are restored when charging.
chargefficiency: 200

#This is option to turn off crafting
cancraft: true

#name, durability and lore can be changed.
boots:
  name: "CloudStep Boots"
  #This is time in seconds how long boots can fly
  durability: 1800
  lore:
    - "But it has its limits"
premiumboots:
  name: "SkyCharge Boots"
  #This is time in seconds how long boots can fly
  durability: 1800
  lore:
    - "You can charge it back with"
    - "{*}"
#{*} is to show chargeitem in lore, but it's not required.
