firstline: "Allows you to fly like you always wanted"
chargeitem: "WIND_CHARGE"
chargefficiency: 200
cancraft: true
cancharge: true
boots:
  name: "Hermes Boots"
  durability: 1800
  lore:
    - "But it has its limits"
premiumboots:
  name: "Premium Hermes Boots"
  durability: 1800
  lore:
    - "You can charge it back with"