name: FlyingBoots
version: '${project.version}'
main: com.hemostaza.creativeboots.CreativeBoots
api-version: '1.21'
commands:
  giveboots:
    description: "Give boots to player"
    usage: "/giveboots <player> <normal/premium>"
    aliases: ["givehermes","gboots"]
    permission: op
