name: creativeElytra
version: '1.0-SNAPSHOT'
main: com.hemostaza.creativeElytra.CreativeElytra
api-version: '1.21'
commands:
  celytra:
    description: "chuj"
    usage: "/celytra <subcommand>"
    aliases: ["cel"]
